# Generated by Django 2.2.16 on 2022-09-17 14:35

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220917_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, help_text='Укажите краткое описание группы', max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Введите дату выпуска', validators=[reviews.validators.validate_year], verbose_name='Дата выпуска'),
        ),
    ]
