# Generated by Django 2.2.16 on 2022-09-17 14:39

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220917_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[reviews.validators.validate_rating]),
        ),
    ]
