# Generated by Django 2.2.16 on 2022-09-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220917_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': (('-id',),), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
